# Generated by Django 5.1.4 on 2024-12-24 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('carga_horaria_diaria', models.IntegerField(default=8, verbose_name='Carga Horaria')),
                ('saldo_horas', models.FloatField(default=0.0, verbose_name='Saldo de Horas')),
                ('data_admissao', models.DateField(auto_now_add=True, verbose_name='Data de Admissão')),
                ('data_demissao', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('horas_trabalhadas', models.IntegerField(blank=True, null=True, verbose_name='Horas Trabalhadas')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='aplic.funcionario')),
            ],
        ),
    ]
